#!/bin/sh
#
# modify-package-dates <date> <packages>...
#
# <date> should be a date in any form 
# <packages> should be a list of package names
#
# Note that some package names are special:
#
#  GPE - this is turned into the list of packages that make up GPE
#
# NOTE: works inside or outside scratchbox environment but current
# directory must be mud-builder directory
#

date=`date -d "$1" +%Y%m%d`
shift

# Remember where the scripts live
export SCRIPTS=`dirname $0`
if [ "${SCRIPTS:0:1}" != "/" -a "${SCRIPTS:0:1}" != "~" ]
then
  SCRIPTS=`pwd`/$SCRIPTS
fi

for pkg in `$SCRIPTS/expand-package-names "$@"`
do
    file=packages/$pkg.xml
    echo "editing $file"
    sed -i -e "/^[ \\t]*date=\"[0-9]*\"\$/s/[0-9][0-9]*/$date/" $file
done